<form action="#" method="post" enctype="multipart/form-data">
    <div class="container-fluid">
        <div class="container left-container">
            <h1>Add</h1>
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" class="form-control" id="name" name="name" value="">
            </div>
            <div class="form-group">
                <label for="link">Link</label>
                <input type="hidden" name="MAX_FILE_SIZE" value="10000000000" />
                <input type="file" class="form-control" name="uploadedfile" value="">
            </div>
        </div>
        <aside class="right-panel">
            <div class="panel-box">
                <div class="container-fluid text-center">
                    <input type="submit" value="&plus;&nbsp;<?php echo $this->translate('Add'); ?>" class="btn btn-block btn-success">
                    <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'navigation', 'action' => 'list')); ?>" class="btn btn-block btn-danger">
                        <?php echo $this->translate('Cancel'); ?>
                    </a>
                </div>
            </div>

            <div class="panel-box">
                <div class="container-fluid">
                    <div class="form-group">
                        <label for="order">Cena</label>
                        <input type="text" class="form-control" id="price" name="price" value="0">
                    </div>
                </div>
            </div>
        </aside>
    </div>
</form>