<form action="#" method="post" enctype="multipart/form-data">
    <div class="container-fluid">
        <div class="container left-container">
            <h1>Dodaj produkt</h1>
            <div class="form-group">
                <label for="name">Nazwa</label>
                <input type="text" class="form-control" id="name" name="name" value="<?php echo $this->name ?>">
                <span class="text-danger error-message"><?php if (isset($this->errors['login'])) echo $this->errors['name'] ?></span>
            </div>
            <div class="form-group">
                <label for="description">Opis</label>
                <textarea class="form-control" id="description" name="description"><?php echo $this->description ?></textarea>
                <span class="text-danger error-message"><?php if (isset($this->errors['login'])) echo $this->errors['description'] ?></span>
            </div>
            <div class="form-group">
                <label for="images">Zdjęcia</label>
                <input type="hidden" name="MAX_FILE_SIZE" value="10000000000"/>
                <input type="file" class="form-control" name="uploadedfile[]" id="images"  onchange="readURL(this);" value="" multiple>
                <span class="text-danger error-message"><?php if (isset($this->errors['login'])) echo $this->errors['file'] ?></span>
            </div>
            <div class="well images"></div>
            <?php var_dump($this->msg); ?>
        </div>
        <aside class="right-panel">
            <div class="panel-box">
                <div class="container-fluid text-center">
                    <input type="submit" value="&plus;&nbsp;Dodaj" class="btn btn-block btn-success">
                    <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'products', 'action' => 'list')); ?>"
                       class="btn btn-block btn-danger">
                        Anuluj
                    </a>
                </div>
            </div>

            <div class="panel-box">
                <div class="container-fluid">
                    <div class="form-group">
                        <label for="price">Cena</label>
                        <input type="text" class="form-control" id="price" name="price" value="<?php echo $this->price ?>">
                        <span class="text-danger error-message"><?php if (isset($this->errors['login'])) echo $this->errors['price'] ?></span>
                    </div>
                    <div class="form-group">
                        <label for="quantity">Ilość</label>
                        <input type="number" class="form-control" id="quantity" name="quantity" value="<?php echo $this->quantity ?>">
                        <span class="text-danger error-message"><?php if (isset($this->errors['login'])) echo $this->errors['quantity'] ?></span>
                    </div>
                    <div class="form-group">
                        <label for="category">Kategoria</label>
                        <select name="category_id" id="category">
                            <?php echo $this->Categories('select'); ?>
                        </select>
                    </div>
                </div>
            </div>
        </aside>
    </div>
</form>
<script>
    var readURL = function(event) {
        $('.well.images').html('').hide();
        for(var i=0; i<event.files.length; i++){
            var id="image"+i;
            $('.well.images').show();
            $('.well.images').append('<img id="'+id+'" class="preview_imge" title="edit">');
            var output = document.getElementById(id);

            output.src = URL.createObjectURL(event.files[i]);
        }
    };
</script>