<form action="#" method="post" enctype="multipart/form-data">
    <div class="container-fluid">
        <div class="container left-container">
            <h1>Dodaj produkt</h1>
            <div class="form-group">
                <label for="name">Nazwa</label>
                <input type="text" class="form-control" id="name" name="name" value="">
            </div>
            <div class="form-group">
                <label for="name">Opis</label>
                <textarea class="form-control" id="description" name="description"></textarea>
            </div>
            <div class="form-group">
                <label for="link">Zdjęcia</label>
                <input type="hidden" name="MAX_FILE_SIZE" value="10000000000" />
                <input type="file" class="form-control" name="uploadedfile[]" value="" multiple>
            </div>
            <?php var_dump($this->msg);?>
        </div>
        <aside class="right-panel">
            <div class="panel-box">
                <div class="container-fluid text-center">
                    <input type="submit" value="&plus;&nbsp;Dodaj" class="btn btn-block btn-success">
                    <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'navigation', 'action' => 'list')); ?>" class="btn btn-block btn-danger">
                        Anuluj
                    </a>
                </div>
            </div>

            <div class="panel-box">
                <div class="container-fluid">
                    <div class="form-group">
                        <label for="order">Cena</label>
                        <input type="text" class="form-control" id="price" name="price" value="0">
                    </div>
                    <div class="form-group">
                        <label for="order">Ilość</label>
                        <input type="number" class="form-control" id="quantity" name="quantity" value="0">
                    </div>
                </div>
            </div>
        </aside>
    </div>
</form>