<div class="container-fluid">
    <div class="container full-container">
        <div id="action_for_checked">
            <div class="btn-group">
                <button class="btn btn-danger" id="delete_selected" onclick="return confirm('Jesteś pewny?')">
                    <i class="fa fa-trash"></i>&nbsp;
                    Usuń
                </button>
            </div>
        </div>
        <?php if ($this->users): ?>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th style="width: 50px">
                                <input type="checkbox" class="select_all">
                            </th>
                            <th>
                                <a href="<?php echo $this->url(array('controller'=>'users', 'action'=>'list-blocked', 'order'=>'name', 'order_type' => $this->order_type=='asc'?'desc':'asc'))?>">
                                    Nazwa
                                </a>
                            </th>
                            <th>
                                <a href="<?php echo $this->url(array('controller'=>'users', 'action'=>'list-blocked', 'order'=>'email', 'order_type' => $this->order_type=='asc'?'desc':'asc'))?>">
                                    Email
                                </a>
                            </th>
                            <th style="width: 100px">
                                <a href="<?php echo $this->url(array('controller'=>'users', 'action'=>'list-blocked', 'order'=>'status', 'order_type' => $this->order_type=='asc'?'desc':'asc'))?>">
                                    Status
                                </a>
                            </th>
                            <th style="width: 130px">
                                <a href="<?php echo $this->url(array('controller'=>'users', 'action'=>'list-blocked', 'order'=>'type', 'order_type' => $this->order_type=='asc'?'desc':'asc'))?>">
                                    Typ
                                </a>
                            </th>
                            <th style="width: 130px">
                                <a href="<?php echo $this->url(array('controller'=>'users', 'action'=>'list-blocked', 'order'=>'date_register', 'order_type' => $this->order_type=='asc'?'desc':'asc'))?>">
                                    Data rejestracji
                                </a>
                            </th>
                            <th style="width: 130px">
                                Zablokowany przez
                            </th>
                            <th>
                                Powód
                            </th>
                            <th style="width: 130px">
                                <a href="<?php echo $this->url(array('controller'=>'users', 'action'=>'list-blocked', 'order'=>'date_blocked', 'order_type' => $this->order_type=='asc'?'desc':'asc'))?>">
                                    Data blokady
                                </a>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->users as $item): ?>
                            <tr data-id="<?php echo $item->id ?>">
                                <th scope="row">
                                    <input type="checkbox">
                                </th>
                                <td>
                                    <a class="user-banned" href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'users', 'action' => 'edit', 'id' => $item->id)) ?>">
                                        <?php echo $item->first_name.' '.$item->last_name; ?>
                                    </a>
                                </td>
                                <td>
                                    <?php echo $item->email; ?>
                                </td>
                                <td>
                                    <?php echo $item->status; ?>
                                </td>
                                <td>
                                    <?php echo $item->user_type;?>
                                </td>
                                <td class="text-center">
                                    <?php echo $item->date_register;?>
                                </td>
                                <td class="text-center">
                                    <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'users', 'action' => 'edit', 'id' => $item->id)) ?>">
                                        <?php echo $item->user_blocking_name.' ('.$item->user_blocking_type.')'; ?>
                                    </a>
                                </td>
                                <td>
                                    <?php echo $item->blocked_reason;?>
                                </td>
                                <td class="text-center">
                                    <?php echo $item->date_blocked;?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        <?php else: ?>
            pusto
        <?php endif; ?>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('input.select_all').change(function () {
            var $this = $(this);
            $('input:checkbox').each(function () {
                $(this).prop('checked', $this.is(':checked'));
            });
        });
        $('input:checkbox').change(function () {
            if ($('input:checkbox:checked').length) {
                $('#action_for_checked').show();
            } else {
                $('#action_for_checked').hide();
            }
        });

        $('#delete_selected').click(function () {
            var reason = prompt('Podaj powód', '');
            var link = '/admin/users/delete';
            $('input:checkbox:checked').each(function () {
                var id = $(this).parents('tr').data('id');
                if (typeof (id) !== 'undefined') {
                    link += '/id/' +id;
                }
            });
            link += "/reason/"+reason;
            window.location.href = link;
        });
    });
</script>