<?php echo $this->doctype() ?>
<html>
    <head>
        <title>ZrobTo</title>

        <meta charset="utf-8">
        <meta name="application-name" content="SocialZone">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Chrome, Firefox OS and Opera -->
        <meta name="theme-color" content="#4285f4">
        <!-- Windows Phone -->
        <meta name="msapplication-navbutton-color" content="#4285f4">
        <!-- iOS Safari -->
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
        <meta name="apple-mobile-web-app-capable" content="yes">

        <link rel="stylesheet" href="/css/bootstrap.min.css">
        <link href="/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
        <link rel="stylesheet" type="text/css" href="/css/styles.css">

        <link rel="stylesheet" type="text/css" href="/modules/general/css/style.css">

        <link rel="icon" href="/images/favicon.png" sizes="16x16" type="image/png"/>

        <script src="/js/jquery/jquery-2.1.4.min.js"></script>
        <script src="/js/bootstrap.min.js"></script>

        <script src="/modules/general/js/main.js"></script>

    </head>
    <body>
        <header id="page-top">
            <nav class="navbar navbar-default navbar-fixed-top top-nav">
                <div class="container">
                    <div class="navbar-header page-scroll">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
                            <i class="fa fa-bars"></i>
                        </button>
                        <a class="navbar-brand" href="#page-top">SocialZone</a>
                    </div>
                    <form class="navbar-form" action="/search" role="search" id="search-form" method="post" novalidate="true", autocomplete="off">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="<?php echo $this->translate('Search') ?>" name="q">
                            <div class="input-group-btn">
                                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                            </div>
                            <div id="search-results"></div>
                        </div>
                    </form>
                </div>
            </nav>
        </header>

        <section id="site-content">
            <div class="sidebar">
                <?php echo $this->Categories();?>
            </div>
            <?php echo $this->layout()->content ?>
        </section>
        <!-- Modal -->
        <div id="preview-user" class="modal fade" role="dialog">
            <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title"><?php echo $this->translate('User preview') ?></h4>
                    </div>
                    <div class="modal-body">
                        <div class="row preview">

                        </div>
                        <i class='fa fa-spinner fa-spin '></i>

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('Close') ?></button>
                    </div>
                </div>

            </div>
        </div>

        <footer>
            <div class="footer-above">
                <div class="container">

                </div>
            </div>

            <div class="footer-below">
                <div class="container">
                    Copyright &copy; <a href="https://github.com/rtCoder">rtCoder</a> 2016
                    <br>
                    <a href="/admin/">Admin</a>
                </div>
            </div>
        </footer>
    </body>
</html>
