<form action="#" method="post">
    <div class="container-fluid">
        <div class="container left-container">
            <h1>Edit</h1>
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" class="form-control" id="name" name="name" value="<?php echo $this->item->name ?>">
            </div>
            <div class="form-group">
                <label for="link">Link</label>
                <input type="text" class="form-control" id="order" name="link" value="<?php echo $this->item->link ?>">
            </div>
        </div>
        <aside class="right-panel">
            <div class="panel-box">
                <div class="container-fluid text-center">
                    <input type="submit" value="&plus;&nbsp;Zapisz" class="btn btn-block btn-success">
                    <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'navigation', 'action' => 'list')); ?>" class="btn btn-block btn-primary">
                        Anuluj
                    </a>
                    <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'navigation', 'action' => 'delete', 'id' => $this->item->id)); ?>" class="btn btn-block btn-danger" style="margin-top: 20px">
                        &times;&nbsp;Usuń
                    </a>
                </div>
            </div>

            <div class="panel-box">
                <div class="container-fluid">
                    <div class="form-group">
                        <label for="show_in_menu">Show in menu</label>
                        <select class="form-control" name="show_in_menu" id="show_in_menu">
                            <option value="1" <?php if ($this->item->show_in_menu == 1) echo 'selected'; ?>>Show</option>
                            <option value="0" <?php if ($this->item->show_in_menu == 0) echo 'selected'; ?>>Hide</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="order">Order</label>
                        <input type="text" class="form-control" id="order" name="order" value="<?php echo $this->item->order_list ?>">
                    </div>
                    <div class="form-group">
                        <label for="parent_id">Parent</label>
                        <select class="form-control" name="parent_id" id="parent_id">
                            <option value="0">NONE</option>
                            <?php foreach ($this->parents as $parent): ?>
                                <option value="<?php echo $parent->id ?>" <?php if ($parent->id == $this->item->parent_id) echo 'selected'; ?>>
                                    <?php echo $parent->name ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>
            </div>
        </aside>
    </div>
</form>